// GERADO por tools/build_votacao_data.py. Não editar à mão.
export const TRILHA: Record<string, string> = {
  "conector": "Instituições",
  "iniciativa": "Instituições",
  "mente": "Instituições",
  "transformador": "Agências",
  "acelerador": "Agências",
  "espirito": "Agências",
};

// slug do finalista -> categoria
export const FINALISTAS: Record<string, string> = {
  "anderson-bertin": "conector",
  "anderson-pacheco": "conector",
  "andressa-chantre": "conector",
  "gustavo-gandra": "conector",
  "murilo-fernandes": "conector",
  "camila-viana": "iniciativa",
  "erica-pereira": "iniciativa",
  "fabio-carola": "iniciativa",
  "francielly-gnoatto": "iniciativa",
  "tatiana-menniti": "iniciativa",
  "eddy-leite": "mente",
  "guilherme-garcia": "mente",
  "gustavo-machado": "mente",
  "igor-marinho": "mente",
  "vitor-alvarino": "mente",
  "carla-mussoi": "transformador",
  "daniel-lara": "transformador",
  "diego-paiva": "transformador",
  "diogo-jansen": "transformador",
  "hanna-alves": "transformador",
  "eduardo-henrique": "acelerador",
  "karen-oliveira": "acelerador",
  "matheus-campos": "acelerador",
  "rafaela-monteiro": "acelerador",
  "victor-luraschi": "acelerador",
  "daniel-cuenca": "espirito",
  "eduardo-frigo": "espirito",
  "fernanda-rocha": "espirito",
  "myllena-pontes": "espirito",
  "vitor-cruz": "espirito",
  "vivi-lac": "espirito",
};
